apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-policy-2
spec:
  podSelector: 
    matchLabels: {}
  policyTypes:
  - Ingress
  ingress:
  - from: #allow
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: app1