apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: datadog-operator
  namespace: openshift-operators #global operator, cannot target a specific namespace
spec:
  channel: stable
  installPlanApproval: Automatic
  name: datadog-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
  webhookEnabled: true