apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: ggithubcom-pnminh-acm-notes
  namespace: ggithubcom-pnminh-acm-notes-ns
spec:
  type: Git
  pathname: 'https://github.com/pnminh/acm-notes'