apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: examples/datadog/using-operatorhub
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: datadog
  name: datadog-subscription-1
  namespace: openshift-operators
spec:
  channel: ggithubcom-pnminh-acm-notes-ns/ggithubcom-pnminh-acm-notes
  placement:
    placementRef:
      kind: Placement
      name: datadog-placement-1