kind: Secret
apiVersion: v1
metadata:
  name: alertmanager-example
stringData:
  alertmanager.yaml: |
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'webhook'
    receivers:
    - name: 'webhook'
      webhook_configs:
      - url: <WEBHOOK_URL>