apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: examples/helloworld/base/deploy
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: hello-world
  name: hello-world-subscription-1  
  namespace: hello-world  
spec:
  channel: acm-channels/github-acm-notes  
  placement:
    placementRef:
      kind: Placement
      name: hello-world-placement-1