apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-user-workload
stringData:
  alertmanager.yaml: |
    global:
      slack_api_url: <SLACK_API_URL>
    route:
      receiver: Default
      group_by: [alertname]
    receivers:
      - name: Default
        slack_configs:
          - channel: "#for-testing"
            send_resolved: true