apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: network-policy-creator-binding
subjects:
- kind: User
  name: user1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: network-policy-creator
  apiGroup: rbac.authorization.k8s.io