apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-access-app2
subjects:
- kind: User
  name: user1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io