apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: hello-world-placement
  namespace: your-namespace
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
