apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../../base/config/others
namespace: app1
patches:
  - target:
      group: app.k8s.io
      version: v1beta1
      kind: Application
      name: hello-world
    path: application-name-patch.yaml
  - target:
      group: apps.open-cluster-management.io
      version: v1
      kind: Subscription
      name: hello-world-subscription-1
    path: subscription-git-path-patch.yaml