apiVersion: datadoghq.com/v2alpha1 #datadog-secret already created on openshift-operators ns
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key